/**
 * Template catalogue — the 14 wedding designs shown in the mockup gallery.
 * `grad`/`ink`/`palette` drive the preview card; `format`/`styles` drive the filters.
 */

export const FORMATS = [
  { id: "todas", label: "Todas" },
  { id: "una-pagina", label: "Una página" },
  { id: "libro", label: "Libro" },
];

export const STYLES = [
  "Playa", "Tropical", "Romántico", "Mediterráneo", "Acuarela", "Floral",
  "Clásico", "Lujo", "Real", "Jardín", "Moderno", "Minimalista", "Vintage",
];

export const TEMPLATES = [
  {
    slug: "beach-romance",
    code: "A0",
    name: "Beach Romance",
    best: true,
    format: "una-pagina",
    ink: "#FFF7F1",
    grad: "linear-gradient(155deg,#F6C79A 0%,#E8927C 52%,#2E5E6E 100%)",
    palette: ["#F6C79A", "#E8927C", "#2E5E6E"],
    styles: ["Playa", "Tropical", "Romántico"],
    desc: "Un atardecer dorado junto al mar, con detalles tropicales para una boda con los pies en la arena.",
  },
  {
    slug: "gondola-dream",
    code: "A1",
    name: "Gondola Dream",
    best: true,
    format: "una-pagina",
    ink: "#3A4A63",
    grad: "linear-gradient(155deg,#CFE0F0 0%,#E9D3DE 52%,#A8C0D8 100%)",
    palette: ["#CFE0F0", "#E9D3DE", "#A8C0D8"],
    styles: ["Mediterráneo", "Acuarela", "Romántico"],
    desc: "Una escapada veneciana en tonos pastel, con la elegancia serena de los canales al atardecer.",
  },
  {
    slug: "classy-floral",
    code: "A2",
    name: "Classy Floral",
    best: true,
    format: "una-pagina",
    ink: "#6B5B3E",
    grad: "linear-gradient(155deg,#F3EEE2 0%,#E7D9C0 52%,#C9B892 100%)",
    palette: ["#F3EEE2", "#E7D9C0", "#C9B892"],
    styles: ["Floral", "Clásico", "Romántico"],
    desc: "Romance atemporal con ilustraciones florales delicadas y detalles dorados.",
  },
  {
    slug: "elegant-royal",
    code: "A3",
    name: "Elegant Royal",
    best: true,
    format: "una-pagina",
    ink: "#F4E3B8",
    grad: "linear-gradient(155deg,#2A2320 0%,#4A3B2A 52%,#C9A24B 100%)",
    palette: ["#2A2320", "#4A3B2A", "#C9A24B"],
    styles: ["Lujo", "Real", "Clásico"],
    desc: "Oro sobre fondos oscuros: dramático, opulento e inolvidable.",
  },
  {
    slug: "dolce-italia",
    code: "A4",
    name: "Dolce Italia",
    best: false,
    format: "una-pagina",
    ink: "#FFF7EC",
    grad: "linear-gradient(155deg,#E7CBA0 0%,#C98A5A 52%,#7A8B4F 100%)",
    palette: ["#E7CBA0", "#C98A5A", "#7A8B4F"],
    styles: ["Mediterráneo", "Jardín", "Moderno"],
    desc: "La calidez toscana se encuentra con la elegancia moderna, entre jardines y terracota.",
  },
  {
    slug: "eternal-navy",
    code: "A5",
    name: "Eternal Navy",
    best: false,
    format: "una-pagina",
    ink: "#EAD9A8",
    grad: "linear-gradient(155deg,#1E2A44 0%,#2C3E60 52%,#C9A24B 100%)",
    palette: ["#1E2A44", "#2C3E60", "#C9A24B"],
    styles: ["Clásico", "Lujo", "Moderno"],
    desc: "Azul noche con toques dorados, para una celebración elegante y serena.",
  },
  {
    slug: "tuscan-wine",
    code: "A6",
    name: "Tuscan Wine",
    best: false,
    format: "una-pagina",
    ink: "#F0D9C0",
    grad: "linear-gradient(155deg,#6E2433 0%,#4A1E2A 52%,#8A5A3C 100%)",
    palette: ["#6E2433", "#4A1E2A", "#8A5A3C"],
    styles: ["Mediterráneo", "Vintage", "Lujo"],
    desc: "Tonos vino profundos y el aroma de un verano italiano entre viñedos.",
  },
  {
    slug: "quiet-luxury",
    code: "A7",
    name: "Quiet Luxury",
    best: false,
    format: "una-pagina",
    ink: "#4A403B",
    grad: "linear-gradient(155deg,#E9D7D2 0%,#D8C3BC 52%,#B7A9A0 100%)",
    palette: ["#E9D7D2", "#D8C3BC", "#B7A9A0"],
    styles: ["Minimalista", "Floral", "Romántico"],
    desc: "Flores sutiles y una atmósfera romántica que se adapta a cualquier estilo de boda.",
  },
  {
    slug: "blue-rose-garden",
    code: "A8",
    name: "Blue Rose Garden",
    best: false,
    format: "una-pagina",
    ink: "#2E4653",
    grad: "linear-gradient(155deg,#C7DCE8 0%,#A9C7B0 52%,#7FA6C0 100%)",
    palette: ["#C7DCE8", "#A9C7B0", "#7FA6C0"],
    styles: ["Jardín", "Acuarela", "Romántico"],
    desc: "Un jardín encantado en acuarela, con rosas azules y aire romántico.",
  },
  {
    slug: "dark-blue-garden",
    code: "A9",
    name: "Dark Blue Garden",
    best: false,
    format: "una-pagina",
    ink: "#E7D3A0",
    grad: "linear-gradient(155deg,#14233F 0%,#22304C 52%,#B8934A 100%)",
    palette: ["#14233F", "#22304C", "#B8934A"],
    styles: ["Jardín", "Lujo", "Clásico"],
    desc: "Un jardín nocturno en azul profundo y oro, íntimo y sofisticado.",
  },
  {
    slug: "french-village",
    code: "A10",
    name: "French Village",
    best: false,
    format: "una-pagina",
    ink: "#4B5A43",
    grad: "linear-gradient(155deg,#DDE8D2 0%,#EAD5DE 52%,#C4D3B0 100%)",
    palette: ["#DDE8D2", "#EAD5DE", "#C4D3B0"],
    styles: ["Acuarela", "Jardín", "Vintage"],
    desc: "Un pueblo francés en acuarela, entre flores pastel y encanto rural.",
  },
  {
    slug: "jardin-de-fleurs",
    code: "A11",
    name: "Jardin de Fleurs",
    best: false,
    format: "libro",
    ink: "#4A3B2A",
    grad: "linear-gradient(155deg,#E7D8C0 0%,#CDB795 52%,#9A7F5E 100%)",
    palette: ["#E7D8C0", "#CDB795", "#9A7F5E"],
    styles: ["Vintage", "Floral", "Clásico"],
    desc: "Grabados vintage en sepia, como un herbario botánico hecho a mano.",
  },
  {
    slug: "soft-floral-book",
    code: "A12",
    name: "Soft Floral Book",
    best: false,
    format: "libro",
    ink: "#6B4A52",
    grad: "linear-gradient(155deg,#F3E1E4 0%,#E8D0D6 52%,#D8BCC4 100%)",
    palette: ["#F3E1E4", "#E8D0D6", "#D8BCC4"],
    styles: ["Floral", "Romántico", "Clásico"],
    desc: "Flores suaves y elegancia atemporal en formato libro.",
  },
  {
    slug: "ciel-divin",
    code: "A13",
    name: "Ciel Divin",
    best: false,
    format: "una-pagina",
    ink: "#2E4A63",
    grad: "linear-gradient(155deg,#CFE4F2 0%,#E7EEF5 52%,#A9C7E0 100%)",
    palette: ["#CFE4F2", "#E7EEF5", "#A9C7E0"],
    styles: ["Moderno", "Minimalista", "Clásico"],
    desc: "Un cielo azul divino coronado por una franja dorada.",
  },
];

export function getTemplate(slug) {
  return TEMPLATES.find((t) => t.slug === slug);
}

export function formatLabel(id) {
  return FORMATS.find((f) => f.id === id)?.label ?? "Una página";
}
